// 100 sample prompts for the 🎲 Random button.
// Curated for FLUX models: photoreal + stylized, varied subjects/moods,
// 1–2 sentences each. Edit freely.
window.SAMPLE_PROMPTS = [
  // ─── Landscapes (15)
  "A misty pine forest at dawn with golden sunbeams cutting through the trees, cinematic, 35mm",
  "A vast desert with crimson sand dunes under a turquoise sky, dramatic shadows",
  "A frozen alpine lake reflecting jagged snow-capped peaks at sunrise",
  "Bioluminescent jungle at midnight, glowing blue mushrooms, mossy ground",
  "Storm clouds rolling over a wheat field at golden hour, dramatic light",
  "A coastal cliff overlooking a turquoise sea, lighthouse in the distance",
  "Cherry blossom path through a Kyoto temple garden, soft afternoon light",
  "Otherworldly salt flats reflecting an aurora, ultra wide shot",
  "Sun-dappled aspen grove in autumn, leaves drifting through warm light",
  "Volcanic landscape with rivers of glowing lava under a starry sky",
  "Rolling green hills of Ireland with stone walls and grazing sheep",
  "A frozen waterfall in a hidden canyon, ice sculpted by wind",
  "Tropical beach at sunset, palm trees silhouetted against magenta clouds",
  "Mossy old-growth forest in the Pacific Northwest, rays through canopy",
  "Tibetan plateau at dawn, snow-capped peaks, prayer flags fluttering",

  // ─── Cityscapes (15)
  "Tokyo street at night in the rain, neon reflections, cyberpunk, cinematic",
  "A bustling Marrakech souk filled with spices and glowing lanterns",
  "Empty Paris boulevard at dawn, cobblestones wet from rain, soft pastels",
  "New York rooftop bar at golden hour, skyline silhouette in the distance",
  "A futuristic megacity with floating cars and holographic billboards",
  "Venice canal at sunset, gondolas, warm light on weathered buildings",
  "Subway tunnel with graffiti, dramatic single-point perspective",
  "Hong Kong harbor at dusk, illuminated junks, dense towers behind",
  "Steampunk Victorian London street with brass-fitted dirigibles overhead",
  "Quiet Lisbon alley with hanging laundry, golden hour, soft warm light",
  "Brutalist concrete library, cathedral-like interior, dust-lit beams",
  "Hidden Kyoto teahouse alley at dusk, paper lanterns, light snow",
  "Mumbai monsoon street, yellow taxis, vibrant umbrellas, tropical rain",
  "Underwater city domes with bioluminescent algae illuminating glass walls",
  "Tehran rooftop view at sunset, distant mountains, layered cityscape",

  // ─── Portraits (15)
  "Close-up portrait of an elderly fisherman in Lisbon, weathered face, soft window light",
  "A young Inuit woman in a fur-lined parka, breath visible, snow softly falling",
  "Portrait of a samurai meditating in a bamboo forest, dramatic side lighting",
  "Renaissance-style oil portrait of a tabby cat in noble dress",
  "A wise old librarian surrounded by floating books, dust motes in afternoon light",
  "Cyberpunk hacker with neon-lit augments, holographic interface around her",
  "Botanical illustration of a fox amid wildflowers, vintage scientific style",
  "Movie still of a 1940s detective in a smoky bar, low key lighting, film noir",
  "Studio portrait of a ballerina mid-leap, dramatic single spotlight",
  "Astronaut helmet reflecting an alien landscape, ultra-detailed visor reflection",
  "Geisha applying makeup in front of a paper-lantern lit mirror",
  "Photoreal portrait of a child holding fireflies in cupped hands at twilight",
  "Stylized illustration of a wizard brewing potions in a cluttered tower",
  "A pearl diver emerging from teal water, droplets sparkling in sun",
  "Old vinyl-shop owner with thick glasses, rows of records in the background",

  // ─── Animals / Nature (15)
  "A snow leopard prowling along a Himalayan ridge at dawn, breath crystallizing",
  "Photoreal close-up of a hummingbird hovering at a hibiscus flower",
  "A blue whale silhouetted from below against sunlit ocean surface",
  "Family of foxes playing in a snow-blanketed clearing at dusk",
  "Hyper-detailed jumping spider portrait, iridescent eyes, macro",
  "A barn owl in flight, wings spread, moonlit wheat field below",
  "Coral reef teeming with neon fish, sun beams piercing turquoise water",
  "Wild horses galloping across an Icelandic black sand beach at sunset",
  "A koala asleep in a eucalyptus tree, dappled morning light",
  "School of tuna spiraling in deep blue water, dynamic motion",
  "Polar bear and cub on a melting ice floe, soft pastel sky",
  "Macro shot of a dragonfly perched on a reed, wings catching sunlight",
  "A toucan in a misty rainforest, vivid plumage, soft bokeh",
  "Bioluminescent jellyfish drifting in pitch black ocean depths",
  "Otter floating on its back in a kelp forest, holding a clam",

  // ─── Food / Still Life (10)
  "Steam rising from a bowl of ramen on a wooden counter, dramatic top-down light",
  "Rustic Tuscan dinner table with wine, bread, cheese, olives, golden hour",
  "A perfect cappuccino with latte art on a marble cafe table",
  "Macro photo of a halved pomegranate, jewel-like seeds, dark background",
  "Glass jars of colorful spices on a sunlit kitchen shelf",
  "Cross-section of a sourdough loaf, dramatic crust, soft afternoon light",
  "Vintage tea set on a lace tablecloth with a window-lit floral arrangement",
  "A whiskey on the rocks beside an open leather-bound book, library backdrop",
  "Detailed still life of vegetables and copper pans in a Dutch master style",
  "Cascading honey dripping over fresh figs on a wooden board",

  // ─── Fantasy / Sci-Fi (10)
  "A massive crystal cave with floating glowing shards, lone explorer below",
  "Dragon perched on a Gothic cathedral spire at sunset",
  "Astronaut walking across an alien planet with twin moons in the sky",
  "Floating sky-island village connected by rope bridges, sunset clouds",
  "A grand wizard duel atop a stormy tower, lightning crackling",
  "Steampunk airship docked at a clockwork harbor city",
  "Alien marketplace with strange floating produce and curious shoppers",
  "A robot tending a garden of mechanical flowers in a ruined city",
  "Time-portal arch in a dense forest, ancient runes glowing softly",
  "Underwater civilization with ornate spires and merfolk citizens",

  // ─── Architecture / Interiors (10)
  "Cozy reading nook with a fireplace, snow falling outside the window",
  "Modern Scandinavian living room flooded with morning light, plants everywhere",
  "Grand library hall with sliding ladders and floor-to-ceiling shelves",
  "Japanese minimalist tea room with tatami mats, soft afternoon light",
  "Ornate baroque cathedral interior, candles flickering, golden light",
  "Mid-century modern poolside with palm trees and a vintage car",
  "Industrial loft kitchen with copper pots and exposed brick",
  "Spaceship cockpit windows looking out at a swirling nebula",
  "Hidden speakeasy bar with art deco furnishings, dim amber lighting",
  "Treehouse village deep in a redwood forest, lit by lanterns",

  // ─── Art / Abstract / Stylized (10)
  "An ink-wash painting of a mountain range emerging from mist",
  "Vintage 1960s travel poster of the Greek isles, bold flat colors",
  "Surreal Dali-esque landscape with melting clocks and elongated shadows",
  "Stained-glass window depicting a phoenix rising from flames",
  "Cinematic Wes Anderson scene of a candy-colored hotel facade",
  "Cyber-anime portrait, neon pink and electric blue, glitch effects",
  "Watercolor illustration of a fox curled around a glowing mushroom",
  "Brutalist sculpture park at twilight, monumental concrete forms",
  "Studio Ghibli inspired scene of a girl in a sunflower field",
  "Photoreal macro shot of a vinyl record's grooves under raking light",
];
